              
# Project names should contain only lowercase characters and underscores
name: 'DBTwithSnowflake'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Path configurations for models, test, seeds, macros etc
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed  by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  DBTwithSnowflake:           # project name
    staging:                  # maps to models/staging
      +materialized: views    # staging models as views
    marts:                    # maps to models/marts
      +materialized: table    # marts as tables

