              
# Project names should contain only lowercase characters and underscores
name: 'DBTwithSnowflake'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Path configurations for models, test, seeds, macros etc
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed  by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  DBTwithSnowflake:          # must match folder name inside models/
    staging:                 # models/DBTwithSnowflake/staging
      +materialized: view
    marts:                   # models/DBTwithSnowflake/marts
      +materialized: table

