# dbt_project.yml
# Project names should contain only lowercase characters and underscores
name: 'DBTwithSnowflake'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Path configurations for models, tests, seeds, macros etc
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directory for compiled SQL and packages
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  DBTwithSnowflake:
    staging:              # maps to models/staging
      +materialized: view # staging models as views
    marts:                # maps to models/marts
      +materialized: table # marts as tables

